name: Ocean Snake

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/ocean-snake.svg?color_snake=#006994&color_dots=#e0f7fa,#b2ebf2,#80deea,#4dd0e1,#26c6da
            dist/ocean-dark.svg?palette=github-dark&color_snake=#00acc1
            dist/ocean.gif?color_snake=#0077be&color_dots=#caf0f8,#90e0ef,#00b4d8,#0077b6,#03045e

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}